run:
  timeout: 5m
linters:
  enable:
    - misspell
    - perfsprint
    - noctx
    - gosec
    - misspell
    - promlinter
    - protogetter
    - unused
    - unparam
    - unconvert
    - usestdlibvars
    - errcheck
    - gosimple
    - govet

linters-settings:
  goimports:
    local-prefixes: github.com/beyerleinf/traefik-plugin-rename-header
