name: Multi Platform CI
on: [push, pull_request]

jobs:
  cross:
    name: Multi-Platform
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: "Install dependencies"
        run: "go mod download"

      - name: Test
        run: go test -v -cover ./...
